### ISSUE TITLE
command 'extension.checkDup' not found

### ISSUE THREAD

**Issue by sheldonhull** [jianbingfang/vscode-dup-checker#1]
## error 

```
workbench.main.js:sourcemap:2217 command 'extension.checkDupWithTrim' not found
e.onDidNotificationChange @ workbench.main.js:sourcemap:2217

```

## Configuration 
```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Failed to run the duplicate check, reporting could not find extension. Wanted to report as I didn't see anyone else reporting this issue. Thanks!

**Comment by jianbingfang** [comment]
Hi @sheldonhull , I'm going to close this issue as I assume you have resolved it.
Feel Free to re-open if you still have the problem :-) .
