### ISSUE TITLE
What is the license for this extension?

### ISSUE THREAD

**Issue by jankeromnes** [jianbingfang/vscode-dup-checker#12]
I couldn't find a `LICENSE` file (or a `"license"` entry in `package.json`).

However, an open-source license is required to publish to https://open-vsx.org -- see also https://github.com/open-vsx/publish-extensions/pull/291

Could you please add a license? 🙏

**Comment by jianbingfang** [comment]
Hi @jankeromnes, the MIT license has been added.

**Comment by jankeromnes** [comment]
That's awesome, many thanks! 🚀
