### ISSUE TITLE
Not able to check duplicates using regex

### ISSUE THREAD

**Issue by skirankumar7** [jianbingfang/vscode-dup-checker#7]
Not able to check duplicates using a regex:

It is not working as expected as soon as I enter any text in regex check mode it is not showing results as expected
Showing Assignment to a constant error in the VSCode

**Comment by jianbingfang** [comment]
Yes, it's a terrible bug, sorry for that.
I've fixed it and published a new version v0.1.6 just now, it should be working after the update.

**Comment by skirankumar7** [comment]
I have updated the plugin and checked still it is not working.
could you check once,
Thanks.

**Comment by jianbingfang** [comment]
Hi @skirankumar7 , I have checked again just now, and it works as expected.
Can you provide more info to help me reproduce your problem?

**Comment by skirankumar7** [comment]
For example, I want to find a pattern like
starting with . (dot) followed by any characters
regex: ^.*

**Results showing:** 
top: 100%;
min-width: 118px;
margin: 2px 0 0;
margin-right: -3px;
border: 1px solid transparent !important;
border-radius: 15px !important; line-height: 35px !important;margin-right: 3px;margin-bottom: 10px;
.project-details-responsive .nav.subtabs li.active {
.project-details-responsive .nav.subtabs li.active a {

**Here I need only result like below:**
.project-details-responsive .nav.subtabs li.active {
.project-details-responsive .nav.subtabs li.active a {

**Not the below results :**
top: 100%;
min-width: 118px;
margin: 2px 0 0;
margin-right: -3px;
border: 1px solid transparent !important;
border-radius: 15px !important; line-height: 35px !important;margin-right: 3px;margin-bottom: 10px;

**Comment by jianbingfang** [comment]
I guess you want to find duplicate css classes, and if so the correct regex should be `^\.[\w\-\s\.{]+`.
In fact your pattern `^.*` will match all characters in a string.

**Comment by skirankumar7** [comment]
Yeah @jianbingfang  got it Thanks for regex and clarification
but there are many conditions were the in my code base like 

**For example got below as duplicates:** 
```
.settings-tabs-container .nav-tabs 
.settings-tabs-container .nav-tabs
```


**I have code like this:**

```
.settings-tabs-container .nav-tabs > li > a:hover {color:#2D2E34!important;}
.settings-tabs-container .nav-tabs>li.active>a, 
.settings-tabs-container .nav-tabs>li.active>a:focus, 
.settings-tabs-container .nav-tabs>li.active>a:hover { background-color: #15BDF4; color:#fff!important;
```

where as those are not duplicated classes.
Any idea/help....

**Comment by jianbingfang** [comment]
Then you should include and escape all possible characters in regex, for example `^\.[\w\-\s\.>:,\[\]\*\=]+{`
