### ISSUE TITLE
case insensitive mode ?

### ISSUE THREAD

**Issue by kursatturkay** [jianbingfang/vscode-dup-checker#8]
it would be great if it can detect duplicated lines in case insensitive mode. : \

**Comment by jianbingfang** [comment]
Hi @kursatturkay , actually DupChecker already has a config named `ignoreCase` for your requirement.

You can find it by searching "DupChecker" in `Preferences -> settings`. More instructions are in [Configurations](https://github.com/jianbingfang/vscode-dup-checker#configurations) section in the profile.
