### ISSUE TITLE
Doesn't fully work as expected

### ISSUE THREAD

**Issue by NN---** [jianbingfang/vscode-dup-checker#9]
Given file

```
a=1
b=2
a=3
b=4
```

I expect duplicating lines with trimChars: =

```
a=3
b=4
```

But I get zero
```
------------------ Prepare ------------------
📄Untitled-1
🔍checking duplicates... done (0.001s)
------------------ Results ------------------
⚙️[trimStart] [trimEnd] [trimChars: =]
✅0 duplicate value found in 4 lines:
```

**Comment by jianbingfang** [comment]
Hi @NN--- , "trimChars" only trims the starting and ending chars, so the numbers 1, 2, 3, 4 will break your trim condition.

You could use `regex match` in your case, by entering `\w+=` you will get output:
```
------------------ Prepare ------------------
📄Untitled-2
🔍checking duplicates... done (0.001s)
------------------ Results ------------------
⚙️[trimStart] [trimEnd]
✅2 duplicate values found in 4 lines:
a=
b=
```
And left the unique lines in editor after dedup:
```
a=1
b=2
```

**Comment by NN---** [comment]
It is more complicated.
I have something like:

text_more_text=some_value:word

I wanted to find out all duplicates on the left side.

What I did is removed everything after equals sign and then used finding duplicates.

Can you add feature of finding duplicates before some separator?

**Comment by jianbingfang** [comment]
> What I did is removed everything after equals sign and then used finding duplicates.

The regex pattern `\w+=` did the exactly same thing. And you can try `[^=]+=` if there are some other kinds of characters.

What you need to do here is to define a regex pattern that can capture your target part.

**Comment by NN---** [comment]
Thanks.

Is it possible to go to the duplicate line from the output ?

**Comment by jianbingfang** [comment]
> Thanks.
> 
> Is it possible to go to the duplicate line from the output ?

Hmm... There is a problem: how to decide the line to jump to if multiple duplicates are found?
